branch-defaults:
  default:
    environment: albabasic-dev
    group_suffix: null
  master:
    environment: albabasic-dev
    group_suffix: null
global:
  application_name: albabasic
  branch: null
  default_ec2_keyname: aws-eb-2020
  default_platform: Python 3.6
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
