# Generated by Django 2.1.1 on 2020-01-29 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albalog', '0004_auto_20200129_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Mon', '월'), ('Tue', '화'), ('Wed', '수'), ('Thu', '목'), ('Fri', '금'), ('Sat', '토'), ('Sun', '일')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='albalog.Member')),
            ],
        ),
    ]
