# Generated by Django 2.1.1 on 2020-01-30 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albalog', '0005_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.CharField(choices=[('1', '월'), ('2', '화'), ('3', '수'), ('4', '목'), ('5', '금'), ('6', '토'), ('7', '일')], max_length=10),
        ),
    ]
