# Generated by Django 2.1.1 on 2020-01-30 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albalog', '0006_auto_20200130_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('active', '재직중'), ('inactive', '퇴사')], default='active', max_length=10),
        ),
    ]
