# Generated by Django 2.1.1 on 2020-01-30 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albalog', '0007_member_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='early_leave',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='late_come',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='timetable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='albalog.TimeTable'),
        ),
    ]
