# Generated by Django 3.0.2 on 2020-01-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albalog', '0010_auto_20200131_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='resignation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
