# Generated by Django 3.0.2 on 2020-02-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albalog', '0011_member_resignation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='absence',
            field=models.BooleanField(default=False, verbose_name='부재'),
        ),
        migrations.AddField(
            model_name='work',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='날짜'),
        ),
        migrations.AddField(
            model_name='work',
            name='reason',
            field=models.CharField(blank=True, choices=[(0, '법정휴일'), (1, '약정휴일'), (2, '연차'), (3, '무단결근')], max_length=2, null=True, verbose_name='사유'),
        ),
    ]
