# Generated by Django 3.0.2 on 2020-02-03 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albalog', '0012_auto_20200203_0808'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Work',
            new_name='Attendance',
        ),
    ]
