# Generated by Django 3.0.2 on 2020-02-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albalog', '0013_auto_20200203_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='근무시간'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='early_leave',
            field=models.DurationField(blank=True, null=True, verbose_name='조퇴'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='퇴근일시'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='late_come',
            field=models.DurationField(blank=True, null=True, verbose_name='지각'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='출근일시'),
        ),
    ]
