# Generated by Django 3.0.2 on 2020-02-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albalog', '0015_holidaypolicy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holidaypolicy',
            name='reason',
        ),
        migrations.AddField(
            model_name='holidaypolicy',
            name='type',
            field=models.CharField(blank=True, choices=[(0, '공휴일'), (1, '창립기념일'), (2, '병가'), (3, '경조사'), (4, '기타')], max_length=10, verbose_name='종류'),
        ),
    ]
