# Generated by Django 3.0.2 on 2020-02-03 08:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('albalog', '0016_auto_20200203_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='annual_leave',
            field=models.IntegerField(blank=True, default=0, verbose_name='연차'),
        ),
        migrations.AddField(
            model_name='member',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='입사일'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='weekly_holiday',
            field=models.CharField(blank=True, choices=[('0', '월'), ('1', '화'), ('2', '수'), ('3', '목'), ('4', '금'), ('5', '토'), ('6', '일')], default=6, max_length=1, verbose_name='주휴일'),
        ),
    ]
