# Generated by Django 3.0.2 on 2020-02-03 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albalog', '0017_auto_20200203_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='reason_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='albalog.HolidayPolicy'),
        ),
    ]
