# Generated by Django 3.0.2 on 2020-02-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albalog', '0018_attendance_reason_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='hourly_wage',
            field=models.IntegerField(blank=True, null=True, verbose_name='시급'),
        ),
        migrations.AlterField(
            model_name='member',
            name='resignation_date',
            field=models.DateField(blank=True, null=True, verbose_name='퇴사일'),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('active', '재직중'), ('inactive', '퇴사')], default='active', max_length=10, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='member',
            name='type',
            field=models.CharField(choices=[('manager', '관리자'), ('member', '일반직원')], default='member', max_length=10, verbose_name='권한'),
        ),
    ]
