# Generated by Django 3.0.2 on 2020-02-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albalog', '0019_auto_20200203_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='total_monthly_salary',
        ),
        migrations.AddField(
            model_name='payroll',
            name='base_salary',
            field=models.IntegerField(default=0, verbose_name='기본급'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payroll',
            name='employment_insurance',
            field=models.IntegerField(blank=True, null=True, verbose_name='고용보험'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='gross_pay',
            field=models.IntegerField(blank=True, null=True, verbose_name='지급액계'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='health_insurance',
            field=models.IntegerField(blank=True, null=True, verbose_name='건강보험'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='income_tax',
            field=models.IntegerField(blank=True, null=True, verbose_name='소득세'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='local_income_tax',
            field=models.IntegerField(blank=True, null=True, verbose_name='지방소득세'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='long_term_care_insurance',
            field=models.IntegerField(blank=True, null=True, verbose_name='장기요양보험'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='national_pension',
            field=models.IntegerField(blank=True, null=True, verbose_name='국민연금'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='net_pay',
            field=models.IntegerField(default=0, verbose_name='차인지급액'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payroll',
            name='sum_of_deductions',
            field=models.IntegerField(blank=True, null=True, verbose_name='공제액계'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='weekly_holiday_allowance',
            field=models.IntegerField(blank=True, null=True, verbose_name='주휴수당'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='working_days',
            field=models.IntegerField(default=0, verbose_name='월 근로일수'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payroll',
            name='working_hours',
            field=models.IntegerField(default=0, verbose_name='월 근로시간'),
            preserve_default=False,
        ),
    ]
