# Generated by Django 3.0.2 on 2020-02-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albalog', '0020_auto_20200204_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='gross_pay',
            field=models.IntegerField(default=0, verbose_name='지급액계'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payroll',
            name='sum_of_deductions',
            field=models.IntegerField(default=0, verbose_name='공제액계'),
            preserve_default=False,
        ),
    ]
