# Generated by Django 3.0.2 on 2020-02-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albalog', '0021_auto_20200204_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='employment_insurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='health_insurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='industrial_accident_comp_insurance',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='member',
            name='national_pension',
            field=models.BooleanField(default=False),
        ),
    ]
