# Generated by Django 3.0.2 on 2020-02-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albalog', '0022_auto_20200204_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidaypolicy',
            name='memo',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='비고'),
        ),
        migrations.AlterField(
            model_name='holidaypolicy',
            name='type',
            field=models.CharField(choices=[(0, '공휴일'), (1, '창립기념일'), (2, '병가'), (3, '경조사'), (4, '기타')], max_length=10, verbose_name='종류'),
        ),
    ]
