# Generated by Django 3.0.2 on 2020-02-06 16:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albalog', '0023_auto_20200204_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='timetable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='albalog.TimeTable'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albalog.Member'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.CheckConstraint(check=models.Q(duration__gt=datetime.timedelta(0)), name='duration_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('date', 'timetable'), name='unique_date_timetable'),
        ),
    ]
