# Generated by Django 3.0.2 on 2020-02-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albalog', '0024_auto_20200206_1606'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payroll',
            constraint=models.UniqueConstraint(fields=('member', 'year', 'month'), name='unique_year_month_member'),
        ),
    ]
