# Generated by Django 3.0.2 on 2020-02-07 11:54
from django.contrib.postgres.operations import BtreeGistExtension

import albalog.models
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albalog', '0025_auto_20200206_1710'),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('end_time__isnull', False), ('start_time__isnull', False)), expressions=((albalog.models.TsTzRange('start_time', 'end_time', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&'), ('member', '=')), name='exclude_overlapping_attendance'),
        ),
    ]
