# Generated by Django 3.0.2 on 2020-02-07 13:00

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('albalog', '0026_auto_20200207_1154'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.CheckConstraint(check=models.Q(end_time__gt=django.db.models.expressions.F('start_time')), name='end_time_is_greater_than_start_time'),
        ),
    ]
