# Generated by Django 3.0.2 on 2020-02-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albalog', '0027_auto_20200207_1300'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('absence', True), ('timetable__isnull', False)), ('absence', False), _connector='OR'), name='exclude_absence_on_day_off'),
        ),
    ]
