# Generated by Django 3.0.2 on 2020-02-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albalog', '0029_auto_20200207_1453'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='business',
            constraint=models.UniqueConstraint(fields=('license_number',), name='unique_license_number'),
        ),
    ]
