# Generated by Django 3.0.2 on 2020-02-07 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albalog', '0030_auto_20200207_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='end_next_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albalog.Business'),
        ),
    ]
