# Generated by Django 3.0.2 on 2020-02-07 16:44

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('albalog', '0031_auto_20200207_1638'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='timetable',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('end_next_day', False), ('end_time__gt', django.db.models.expressions.F('start_time'))), ('end_next_day', True), _connector='OR'), name='end_time_is_greater_than_start_time_if_end_on_same_day'),
        ),
    ]
