# Generated by Django 3.0.2 on 2020-02-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albalog', '0032_auto_20200207_1644'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='member',
            constraint=models.CheckConstraint(check=models.Q(hourly_wage__gt=0), name='hourly_wage_is_over_0'),
        ),
    ]
