# Generated by Django 3.0.2 on 2020-02-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albalog', '0033_auto_20200207_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidaypolicy',
            name='memo',
            field=models.TextField(blank=True, default='', max_length=50, verbose_name='비고'),
        ),
        migrations.AlterField(
            model_name='member',
            name='annual_leave',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='연차'),
        ),
        migrations.AlterField(
            model_name='member',
            name='hourly_wage',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='시급'),
        ),
        migrations.AlterField(
            model_name='member',
            name='weekly_holiday',
            field=models.PositiveSmallIntegerField(choices=[(0, '월'), (1, '화'), (2, '수'), (3, '목'), (4, '금'), (5, '토'), (6, '일')], default=6, verbose_name='주휴일'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='base_salary',
            field=models.PositiveIntegerField(verbose_name='기본급'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='gross_pay',
            field=models.PositiveIntegerField(verbose_name='지급액계'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='month',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='weekly_holiday_allowance',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='주휴수당'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='working_days',
            field=models.PositiveSmallIntegerField(verbose_name='월 근로일수'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='working_hours',
            field=models.PositiveSmallIntegerField(verbose_name='월 근로시간'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='year',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
